
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: copa
      POSTGRES_PASSWORD: copa123
      POSTGRES_DB: copa2026
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.9.1
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://copa:copa123@postgres/copa2026
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      _PIP_ADDITIONAL_REQUIREMENTS: 'psycopg2-binary dbt-postgres'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./dbt_project:/opt/airflow/dbt_project
    ports:
      - "8080:8080"
    command: standalone

volumes:
  postgres_data: